"""Added library settings and borrow deadline

Revision ID: 0422a02c566d
Revises: 372b37ccde45
Create Date: 2025-03-26 18:10:05.567527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0422a02c566d'
down_revision: Union[str, None] = '372b37ccde45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_books', sa.Column('deadline', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_books', 'deadline')
    # ### end Alembic commands ###
