"""Add library_book_id to BookMT

Revision ID: 053477f92b35
Revises: 88d022717fb0
Create Date: 2025-03-23 15:32:23.336476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053477f92b35'
down_revision: Union[str, None] = '88d022717fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_mt', sa.Column('library_book_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_library_book_id', 'book_mt', ['lid', 'library_book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_library_book_id', 'book_mt', type_='unique')
    op.drop_column('book_mt', 'library_book_id')
    # ### end Alembic commands ###
