"""Updated tables

Revision ID: 11778445fa88
Revises: 0422a02c566d
Create Date: 2025-03-27 20:25:45.928406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11778445fa88'
down_revision: Union[str, None] = '0422a02c566d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_mt',
    sa.Column('gid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('gid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genre_mt_gid'), 'genre_mt', ['gid'], unique=False)
    op.create_table('memberlist',
    sa.Column('mid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lid'], ['library_mt.lid'], ),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_memberlist_mid'), 'memberlist', ['mid'], unique=False)
    op.create_table('book_genre',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['book_mt.bid'], ),
    sa.ForeignKeyConstraint(['gid'], ['genre_mt.gid'], ),
    sa.PrimaryKeyConstraint('bid', 'gid')
    )
    op.drop_column('book_mt', 'genre')
    op.drop_column('borrow_books', 'latency')
    op.add_column('library_mt', sa.Column('default_borrow_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library_mt', 'default_borrow_duration')
    op.add_column('borrow_books', sa.Column('latency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book_mt', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('book_genre')
    op.drop_index(op.f('ix_memberlist_mid'), table_name='memberlist')
    op.drop_table('memberlist')
    op.drop_index(op.f('ix_genre_mt_gid'), table_name='genre_mt')
    op.drop_table('genre_mt')
    # ### end Alembic commands ###
