"""Updated models

Revision ID: 34ab95655ea8
Revises: 770f24ba37f6
Create Date: 2025-03-18 20:28:34.572058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ab95655ea8'
down_revision: Union[str, None] = '770f24ba37f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_bid', table_name='books')
    op.drop_table('books')
    op.create_unique_constraint(None, 'library_mt', ['phonenumber'])
    op.create_unique_constraint(None, 'library_mt', ['gmail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library_mt', type_='unique')
    op.drop_constraint(None, 'library_mt', type_='unique')
    op.create_table('books',
    sa.Column('bid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bid', name='books_pkey')
    )
    op.create_index('ix_books_bid', 'books', ['bid'], unique=False)
    # ### end Alembic commands ###
