"""Added Librarian model

Revision ID: 53a0418f1102
Revises: a63e7fcd9e87
Create Date: 2025-03-18 20:13:45.228730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a0418f1102'
down_revision: Union[str, None] = 'a63e7fcd9e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_mt',
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('library_pic', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('gmail', sa.String(), nullable=False),
    sa.Column('penaltyrate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('lid')
    )
    op.create_index(op.f('ix_library_mt_lid'), 'library_mt', ['lid'], unique=False)
    op.create_table('librarian',
    sa.Column('lbid', sa.Integer(), nullable=False),
    sa.Column('gmail', sa.String(), nullable=False),
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lid'], ['library_mt.lid'], ),
    sa.PrimaryKeyConstraint('lbid'),
    sa.UniqueConstraint('gmail'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_index(op.f('ix_librarian_lbid'), 'librarian', ['lbid'], unique=False)
    op.drop_index('ix_users_gmail', table_name='users')
    op.create_unique_constraint(None, 'users', ['gmail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_gmail', 'users', ['gmail'], unique=True)
    op.drop_index(op.f('ix_librarian_lbid'), table_name='librarian')
    op.drop_table('librarian')
    op.drop_index(op.f('ix_library_mt_lid'), table_name='library_mt')
    op.drop_table('library_mt')
    # ### end Alembic commands ###
