"""Added LibraryMT, BookMT, BorrowBooks models

Revision ID: 770f24ba37f6
Revises: 53a0418f1102
Create Date: 2025-03-18 20:20:10.202138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770f24ba37f6'
down_revision: Union[str, None] = '53a0418f1102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_index(op.f('ix_books_bid'), 'books', ['bid'], unique=False)
    op.create_table('book_mt',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lid'], ['library_mt.lid'], ),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_index(op.f('ix_book_mt_bid'), 'book_mt', ['bid'], unique=False)
    op.create_table('borrow_books',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('bdate', sa.Date(), nullable=False),
    sa.Column('rdate', sa.Date(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['book_mt.bid'], ),
    sa.ForeignKeyConstraint(['lid'], ['library_mt.lid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_borrow_books_tid'), 'borrow_books', ['tid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_books_tid'), table_name='borrow_books')
    op.drop_table('borrow_books')
    op.drop_index(op.f('ix_book_mt_bid'), table_name='book_mt')
    op.drop_table('book_mt')
    op.drop_index(op.f('ix_books_bid'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
