"""Added available_count to BookMT

Revision ID: 88d022717fb0
Revises: 80a407691b3a
Create Date: 2025-03-20 19:50:58.017801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d022717fb0'
down_revision: Union[str, None] = '80a407691b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_mt', sa.Column('available_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_mt', 'available_count')
    # ### end Alembic commands ###
