"""Recreating correct tables

Revision ID: ede9258232c2
Revises: 34ab95655ea8
Create Date: 2025-03-18 20:30:33.347806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede9258232c2'
down_revision: Union[str, None] = '34ab95655ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_books',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('bdate', sa.Date(), nullable=False),
    sa.Column('rdate', sa.Date(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['book_mt.bid'], ),
    sa.ForeignKeyConstraint(['lid'], ['library_mt.lid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_borrow_books_tid'), 'borrow_books', ['tid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_books_tid'), table_name='borrow_books')
    op.drop_table('borrow_books')
    # ### end Alembic commands ###
